CREATE DATABASE teaspoon_my

USE teaspoon_my


CREATE TABLE sample (
	NO INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100)
);

SHOW TABLES;

INSERT INTO sample VALUES (DEFAULT,'김기태');
INSERT INTO sample VALUES (DEFAULT,'한선');
INSERT INTO sample VALUES (DEFAULT,'이은영');
INSERT INTO sample VALUES (DEFAULT,'서광');
INSERT INTO sample VALUES (DEFAULT,'이소윤');

SELECT * FROM sample


-- commit


CREATE TABLE board(
	seq INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	nickname VARCHAR(20),
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP(),
	visited INT DEFAULT 0
);

SHOW TABLES;

SELECT * FROM board;

INSERT INTO board VALUES(DEFAULT, '샘플 글 제목 1','샘플 글 내용 1','user1',DEFAULT,DEFAULT);
INSERT INTO board VALUES(DEFAULT, '샘플 글 제목 2','샘플 글 내용 2','user2',DEFAULT,DEFAULT);
INSERT INTO board VALUES(DEFAULT, '샘플 글 제목 3','샘플 글 내용 3','user3',DEFAULT,DEFAULT);
INSERT INTO board VALUES(DEFAULT, '샘플 글 제목 4','샘플 글 내용 4','user4',DEFAULT,DEFAULT);
INSERT INTO board VALUES(DEFAULT, '샘플 글 제목 5','샘플 글 내용 5','user5',DEFAULT,DEFAULT);
INSERT INTO board VALUES(DEFAULT, '샘플 글 제목 6','샘플 글 내용 6','user6',DEFAULT,DEFAULT);
board

CREATE TABLE MEMBER (
	id VARCHAR(20) PRIMARY KEY,
	pw VARCHAR(300) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	tel VARCHAR(20) NOT NULL,
	addr1 VARCHAR(200),
	addr2 VARCHAR(100),
	postcode VARCHAR(10),
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP(),
	birth DATE,
	pt INT DEFAULT 0,
	visited INT DEFAULT 0
);

DROP TABLE member
SHOW TABLES 



INSERT INTO MEMBER VALUES ('kim','1234','김철수','kim@teaspoon.co.kr','010-1111-2222','주소1','주소2','112233',DEFAULT,'2000-01-01',default,DEFAULT);
INSERT INTO MEMBER VALUES ('admin','1234','관리자','admin@teaspoon.co.kr','010-1111-1111','주소1','주소2','112233',DEFAULT,'1999-01-01',default,DEFAULT);


SELECT * FROM member


UPDATE member SET pw='$2a$10$PKpa4qNB.m2cSr9akl34Je74UV5X1NL9KlQJ2IoqML7IYxgnSlT7W' WHERE pw='1234';


Create TABLE free(
	bno INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100),
	content VARCHAR(2000),
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP(),
	id VARCHAR(20),
	visited INT DEFAULT 0,
	rec INT DEFAULT 0
);

DROP TABLE free
SHOW tables

SELECT * FROM free
INSERT INTO free VALUES (DEFAULT,'제목1','내용1',DEFAULT,'admin',DEFAULT,default);

SELECT * FROM fileinfo

CREATE TABLE fileinfo(
	NO INT AUTO_INCREMENT PRIMARY KEY,  -- 번호
	articleno varchar(45) DEFAULT NULL,
	saveFolder varchar(45) DEFAULT NULL,
	originFile varchar(45) DEFAULT NULL,
	saveFile varchar(45) DEFAULT NULL
);

CREATE TABLE guestbook (
  articleno int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userid varchar(16) NOT NULL,
  subject varchar(100) NOT NULL,
  content varchar(2000) NOT NULL,
  regtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);